$ hello
Traceback (most recent call last):
  File "/home/archie/.local/bin/hello", line 5, in <module>
    from hello import hello_world
ImportError: cannot import name 'hello_world' from 'hello' (/home/archie/.local/lib/python3.10/site-packages/hello/__init__.py)
